# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "bookmarks", :force => true do |t|
    t.column "title",        :string
    t.column "url",          :string
    t.column "clicks",       :integer
    t.column "last_clicked", :datetime
  end

end
